Remove unnecessary postprocess and change tokenizer
furiosa-ai/llmperf pull request #3
Opened 2024-11-22 04:25 UTC by yw-furiosa

- tokenizer를 `furiosa-llm serve`가 사용하는 tokenizer로 바꿉니다.
- 필요하지 않은 postprocess 과정을 삭제합니다.

2024-11-22 04:36 UTC, yw-furiosa commented
어떤 분께 리뷰를 요청드리면 좋을지 몰라 우선 @n0gu-furiosa 성윤님께 요청드립니다. 함께 검토해주시면 좋을분들이 있으시다면 말씀해주세요

2024-11-22 05:03 UTC, n0gu-furiosa requested changes
Postprocess 동작이 여전히 필요한 맥락이 있는 듯 하여 코멘트 남겼습니다.

ttft가 tpot에 같이 들어가는 부분, `[DONE]` 이 tpot에서 누락된 부분은 놓치고 있었네요..! 이 수정사항은 👍 입니다. 고생하셨습니다!

2024-11-22 05:03 UTC, n0gu-furiosa commented on token_benchmark_ray.py
> +    tokenizer = PreTrainedTokenizerFast.from_pretrained("meta-llama/Meta-Llama-3.1-70B-Instruct")
인자로 전달이 가능하면 좋을 것 같은데요, 마침 `--model` 인자가 뚫려있으니 (저희가 그동안 no-op 인자로 사용하고 있었지만) 아래와 같은 방향은 어떨까요? 
```suggestion
    tokenizer = PreTrainedTokenizerFast.from_pretrained(model)
```

2024-11-22 05:03 UTC, n0gu-furiosa commented on token_benchmark_ray.py
> -        num_output_tokens = get_token_length(gen_text)
get_token_length 를 통해 메트릭을 후처리하는 로직이 여전히 필요하기는 합니다.

furiosa-llm serve 의 구현도 그렇고 아마 OpenAI API 구현도 그럴텐데, 간혹 한 글자가 여러 토큰으로 나뉘어 표현되는 경우 (e.g. "쁐") 깨진 토큰(�)을 응답으로 내보내기보다는 다음 토큰까지 모아서 읽을 수 있는 단위로 보내주도록 되어 있습니다. 이런 케이스를 핸들링하려면 마지막에 생성된 문장을 다시 역으로 encode 해서 토큰 수를 세는 과정이 필요합니다.

2024-11-22 05:03 UTC, n0gu-furiosa commented on token_benchmark_ray.py
> -        num_output_tokens = get_token_length(gen_text)
그나저나 기존 get_token_length 함수가 다음과 같이 구현되어 있는데:

`get_token_length = lambda text: len(tokenizer.encode(text))`

아래와 같은 방식으로 계산하는게 가장 정확하지 않나 싶은데요, 혹시 @dkim-furiosa 님 이 내용 검토좀 부탁드려도 될까요?
* tokenizer.encode 에 `skip_special_tokens=True` 를 명시적으로 전달
* eos 를 고려하여 .encode 한 숫자에 +1 을 더함
  * 엄밀히 따지면 `finish_reason` 이 stop 인지 length 인지에 따라 +1 덧셈 여부가 달라져야 할 것 같은데, 일단은 일괄 +1 로 근사해도 될 것 같습니다.

2024-11-22 05:17 UTC, yw-furiosa commented on token_benchmark_ray.py
> -        num_output_tokens = get_token_length(gen_text)
설명 감사합니다 성윤님. 말씀을 들어보면 정확한 계산을 위해서는 output_token 개수의 재계산이 필요한데, 그러면 다른 metric의 값들도 미묘하게 달라질 것 같습니다. 이를 모두 postprocess로 이 부분에서 재계산하는 것 보다는 client코드 (`openai_chat_completions_client.py`) 에서 올바른 값을 계산 후 넘겨주는 것이 더 좋아 보이는데 어떻게 생각하시나요?

2024-11-22 05:19 UTC, n0gu-furiosa commented on token_benchmark_ray.py
> -        num_output_tokens = get_token_length(gen_text)
토큰 수만 정확하게 처리한다면, 위치는 말씀하신대로 오히려 client 에서 정확히 계산해서 넘겨주는 편이 훨씬 직관적이고 깔끔할 것 같습니다. 👍

2024-11-22 06:00 UTC, yw-furiosa commented on token_benchmark_ray.py
> +    tokenizer = PreTrainedTokenizerFast.from_pretrained("meta-llama/Meta-Llama-3.1-70B-Instruct")
반영했습니다 [122c0aa](https://github.com/furiosa-ai/llmperf/pull/3/commits/122c0aa4e28ca5629c1f17be13d2cad93b46931b)

2024-11-22 06:02 UTC, yw-furiosa commented on token_benchmark_ray.py
> -        num_output_tokens = get_token_length(gen_text)
반영했습니다 [7d4b913](https://github.com/furiosa-ai/llmperf/pull/3/commits/7d4b9133528edce2bfae1ce4ce512e7e7ec5e268). `get_token_len`의 구현도 여기저기 흩어져 있는데 [여기](https://github.com/furiosa-ai/llmperf/pull/3/commits/7d4b9133528edce2bfae1ce4ce512e7e7ec5e268#diff-cfa3488cfff8cdee379ebcf7e90d3e8f8bda09dd2b0ec7487d30739eb7c6d0c1R82)에 정의하고 이것만 사용하도록 수정했습니다. 덕환님 검토해주시면 해당 내용도 여기에 반영하겠습니다.

2024-11-22 06:12 UTC, n0gu-furiosa commented on token_benchmark_ray.py
> +    tokenizer = PreTrainedTokenizerFast.from_pretrained("meta-llama/Meta-Llama-3.1-70B-Instruct")
앗 뒷북 죄송한데 위에 들어간 주석도 지워주시면 감사드리겠습니다. (`# Use same tokenizer with furiosa-llm serve`)

2024-11-22 06:14 UTC, yw-furiosa commented on token_benchmark_ray.py
> +    tokenizer = PreTrainedTokenizerFast.from_pretrained("meta-llama/Meta-Llama-3.1-70B-Instruct")
넵! [a896f9b](https://github.com/furiosa-ai/llmperf/pull/3/commits/a896f9be33122914422e2056e1c980493a8f718b)

2024-12-02 01:49 UTC, yw-furiosa commented on token_benchmark_ray.py
> -        num_output_tokens = get_token_length(gen_text)
@dkim-furiosa 덕환님, 오프라인으로 이야기 나누었던 대로 수정해보았습니다. 확인 부탁드립니다. [f271897](https://github.com/furiosa-ai/llmperf/pull/3/commits/f271897df135677b1117851310dc5baf3ab9aa1f)

@n0gu-furiosa 성윤님께서 맥락을 파악하실 수 있도록 오프라인으로 이야기 한 내용을 간락히 정리해보겠습니다. 혹시 제가 잘못 이해한게 있다면 정정 부탁드립니다 덕환님!
- tokenizer는 Exaone에서 사용하는 AutoTokenizer를 사용
- Exaone은 `BOS`를 붙이지 않기 때문에 `add_special_tokens=False`
- finish_reason을 보고 `DONE` token 포함 여부 결정

2024-12-02 01:54 UTC, yw-furiosa commented
Aramco와 Exaone 평가를 진행해보니 tokenizer나 system prompt등 각 benchmark마다 수정해야 해 주어야 할 부분들이 몇가지 생기네요. 하나의 codebase를 사용하되, benchmark마다 알맞은 set을 사용할 수 있는 좋은 방법이 있을까요? 저는 아래와 같은 옵션들이 떠오르는데 의견 부탁드립니다.
- git branch 분리
- cli option 추가 (ex, `--target aramco`)
- config file 추가

개인적으로는 config file로 benchmark마다 달라지는 부분들을 정의해서 관리하면 어떨까 싶은데 달라지는 부분이 많지 않다면 좀 과한 방법이 될 수 있을 것 같아 다른 분들의 의견을 여쭙고 싶습니다.

2024-12-02 01:56 UTC, n0gu-furiosa commented on token_benchmark_ray.py
> -        num_output_tokens = get_token_length(gen_text)
용우님 공유 감사합니다!

Special token을 제외하는 기능이 encode 에서는 `add_special_tokens=False` 였군요 😅 decode 함수의 인자 (`skip_special_tokens=True`) 와 헷갈렸네요.

2024-12-02 11:32 UTC, dkim-furiosa commented on src/llmperf/common.py
> +    llm_api: str, num_clients: int, get_token_len: Callable
`Callable`에 대해서는 인자 형과 반환 형을 적어주면 좋겠습니다:

```suggestion
    llm_api: str, num_clients: int, get_token_len: Callable[[str], int]
```

다른 곳 `Callable`도 비슷하게 수정하는 게 어떨까 싶습니다.

2024-12-02 11:32 UTC, dkim-furiosa commented on src/llmperf/datasets/__init__.py
>          raise ValueError(f"Not supported dataset {dataset}")
이렇게 하자기 보다는 이렇게도 할 수 있겠다 정도입니다:

```python
def randomly_sample_prompt(
    dataset,
    prompt_tokens_mean,
    prompt_tokens_stddev,
    expect_output_tokens,
    get_token_len,
) -> Tuple[str, int]:
    if dataset == "sonnet":
        f = randomly_sample_sonnet_lines_prompt
    elif dataset == "human-eval":
        f = randomly_sample_human_eval_prompt
    elif dataset == "gpqa":
        f = randomly_sample_gpqa_prompt
    elif dataset == "translation":
        f = randomly_sample_translation_prompt
    else:
        raise ValueError(f"Not supported dataset {dataset}")
    return f(prompt_tokens_mean, prompt_tokens_stddev, expect_output_tokens, get_token_len)
```

2024-12-02 11:32 UTC, dkim-furiosa commented on src/llmperf/datasets/gpqa.py
> +            min_prompt_length = get_token_len(prompt)
https://docs.python.org/3.13/whatsnew/3.8.html#assignment-expressions

```suggestion
        if (token_len := get_token_len(prompt)) < min_prompt_length:
            min_prompt_length = token_len
```

2024-12-03 02:18 UTC, yw-furiosa commented on src/llmperf/common.py
> +    llm_api: str, num_clients: int, get_token_len: Callable
반영했습니다 [15da784](https://github.com/furiosa-ai/llmperf/pull/3/commits/15da7844d8e95f9ae30e6812d90ece8f92258500)

2024-12-03 02:18 UTC, yw-furiosa commented on src/llmperf/datasets/__init__.py
>          raise ValueError(f"Not supported dataset {dataset}")
훨씬 깔끔해지네요. 감사합니다. [90ea7b3](https://github.com/furiosa-ai/llmperf/pull/3/commits/90ea7b3bddfdad1d0531b6368c9105540897728d)

2024-12-03 02:19 UTC, yw-furiosa commented on src/llmperf/datasets/gpqa.py
> +            min_prompt_length = get_token_len(prompt)
반영했습니다. [d42421e](https://github.com/furiosa-ai/llmperf/pull/3/commits/d42421e17d67113adf35f96becfe126a0b735153)

2024-12-03 05:40 UTC, dkim-furiosa commented on src/llmperf/datasets/gpqa.py
> +    get_token_len=Callable[[str], int],
`get_token_len`에 대한 형을 선언하고 있지 않고 기본값으로 지정하고 있습니다.

2024-12-03 06:07 UTC, yw-furiosa commented on src/llmperf/datasets/gpqa.py
> +    get_token_len=Callable[[str], int],
아 제가 이런 실수를 했군요 😅  감사합니다.

2024-12-03 06:13 UTC, dkim-furiosa approved these changes
Looks Good To Me. 👏

2024-12-03 06:51 UTC, yw-furiosa commented
@n0gu-furiosa 성윤님, 확인해주시면 머지하겠습니다!

2024-12-03 07:34 UTC, n0gu-furiosa approved these changes
LGTM 입니다! 고생하셨습니다 👍

2024-12-03 07:40 UTC, merged